services:
  app-db:
    image: postgres:16.1
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=dbuser
      - POSTGRES_DB=postgres
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  app-service:
    build: .
    image: test_effective_mobile-image
    container_name: test_effective_mobile-image
    ports:
      - "8080:8080"
    depends_on:
      - app-db
    environment:
      - TZ=Europe/Samara
      - PGTZ=Europe/Samara
      - SPRING_DATASOURCE_URL=jdbc:postgresql://app-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=12345